# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'feature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfeature.proto\"W\n\x05Value\x12\x11\n\ttimestamp\x18\x01 \x01(\x06\x12\x13\n\x0bstringValue\x18\x02 \x03(\t\x12\x13\n\x0b\x64oubleValue\x18\x03 \x03(\x01\x12\x11\n\tboolValue\x18\x04 \x03(\x08\";\n\rUpdatedEntity\x12\x13\n\x0b\x66\x65\x61tureName\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Value\"N\n\x0eUpdatedFeature\x12\x10\n\x08\x65ntityId\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x06\x12\x17\n\x07history\x18\x03 \x03(\x0b\x32\x06.Value')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUE']._serialized_start=17
  _globals['_VALUE']._serialized_end=104
  _globals['_UPDATEDENTITY']._serialized_start=106
  _globals['_UPDATEDENTITY']._serialized_end=165
  _globals['_UPDATEDFEATURE']._serialized_start=167
  _globals['_UPDATEDFEATURE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
