# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfeature.proto\x12.com.predicti.jobs.batch.feature_sync.generated\"q\n\x05Value\x12\x15\n\reffectiveFrom\x18\x01 \x01(\x10\x12\x13\n\x0bstringValue\x18\x02 \x03(\t\x12\x13\n\x0b\x64oubleValue\x18\x03 \x03(\x01\x12\x11\n\tboolValue\x18\x04 \x03(\x08\x12\x14\n\x0cinstantValue\x18\x05 \x03(\x10\"j\n\rUpdatedEntity\x12\x13\n\x0b\x66\x65\x61tureName\x18\x01 \x01(\t\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.com.predicti.jobs.batch.feature_sync.generated.Value\"\x80\x01\n\x0eUpdatedFeature\x12\x10\n\x08\x65ntityId\x18\x01 \x01(\t\x12\x14\n\x0clastModified\x18\x02 \x01(\x06\x12\x46\n\x07history\x18\x03 \x03(\x0b\x32\x35.com.predicti.jobs.batch.feature_sync.generated.ValueB>\n.com.predicti.jobs.batch.feature_sync.generatedB\x0c\x46\x65\x61tureProto')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n.com.predicti.jobs.batch.feature_sync.generatedB\014FeatureProto'
  _VALUE._serialized_start=65
  _VALUE._serialized_end=178
  _UPDATEDENTITY._serialized_start=180
  _UPDATEDENTITY._serialized_end=286
  _UPDATEDFEATURE._serialized_start=289
  _UPDATEDFEATURE._serialized_end=417
# @@protoc_insertion_point(module_scope)
